### PR TITLE
Update py2exe with upstream, add patch for 

### PR DESCRIPTION
**Pull request by leonardder**
This updates py2exe to master from upstream, including the patch from https://github.com/albertosottile/py2exe/pull/13, which fixes a major bug for us.

### CODE REVIEW

**Comment by leonardder** [comment]
@feerrenrut: This blocks several issues, so if you could review this ASAP, that would be appreciated!

**Comment by feerrenrut** [comment]
This looks fine, but I think this should be merged into `threshold_py3_staging` not `master`?

**Comment by feerrenrut** [comment]
Ignore that last comment... different repo

**Comment by leonardder** [comment]
I've updated the readme as requested.

**Pull request merged**
